export  const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';

// export const GET_ARTICLE_LIST_REQUEST = 'GET_ARTICLE_LIST_REQUEST';
// export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
// export const GET_ARTICLE_LIST_FAILED = 'GET_ARTICLE_LIST_FAILED';
//delete

export const DELETE_ARTICLE_LIST = 'DELETE_ARTICLE_LIST';

// export const DELETE_ARTICLE_LIST_REQUEST = 'DELETE_ARTICLE_LIST_REQUEST';
// export const DELETE_ARTICLE_LIST_SUCCESS = 'DELETE_ARTICLE_LIST_SUCCESS';
// export const DELETE_ARTICLE_LIST_FAILED = 'DELETE_ARTICLE_LIST_FAILED';